### ISSUE TITLE
Bug en la rotación de cámara 

### ISSUE THREAD

**Issue by ChristianCB16** [ChristianCB16/imageTOtext#1]
Al tomar la foto se tiene que rotar la cámara para poder tomar la foto.

**Comment by HugoDoradea14** [comment]
Este bug ha sido solucionado en el commit que actualiza el icono de la app

`        <activity android:name=".MainActivity"
            android:exported="true"
            android:screenOrientation="portrait">`
![Screenshot_20220705_132457_com example textdemo](https://user-images.githubusercontent.com/54194193/177407160-1ce16231-9e9a-46d1-92dc-2199fc7a193b.jpg)
