### ISSUE TITLE
Problema con la creación de herramienta de traducción

### ISSUE THREAD

**Issue by JuanGallard0** [ChristianCB16/imageTOtext#2]
El programa se cierra debido a un error intentando conectarse al servidor de google a la hora de importar los modelos de traducción de lenguaje.
Función problemática: private void translateTextToSpanish(String text, String inputLanguage)  
línea 161

![image](https://user-images.githubusercontent.com/54408047/177254178-bf97ead2-2c03-4fc9-890c-db14280eb872.png)

**Comment by HugoDoradea14** [comment]
Se resolvió añadiendo un valor por defecto en el Spinner de lenguajes: 
`items.add("N/F");` y también verificando su estado antes de realizar la traducción ` if(items.get(0)!="N/F"){`
