### ISSUE TITLE
Error al realizar traduccion

### ISSUE THREAD

**Issue by HugoDoradea14** [ChristianCB16/imageTOtext#4]
El aplicativo solo traduce del ingles a cualquier idioma, cuando se selecciona otro idioma de origen de la traducción no se realiza

**Comment by JuanGallard0** [comment]
Cambio en la función de traducción para crear el objeto traductor dinámicamente.
![image](https://user-images.githubusercontent.com/54408047/177618171-a8283073-8918-499a-b5aa-01598bc65271.png)
